greentea/tgvisd: Fix build error due to td::td_api::message change
In version 1.8.0, the class `td::td_api::message` no longer contains a
field named `->sender_`, instead it uses `->sender_id_`.

This breaks the build:
```
error: no member named 'sender_' in 'td::td_api::message'
```

There is no functional change intended.

Signed-off-by: Ammar Faizi <ammarfaizi2@gmail.com>